const toolInfo = [
  {
    name: 'pen',
    text: 'Pen tool',
    shift: '',
    ctrl: '',
    key: 'P',
  },
  {
    name: 'mirror',
    text: 'Vertical Mirror pen',
    shift: 'Use horizontal and vertical axis',
    ctrl: 'Use horizontal axis',
    key: 'V',
  },
  {
    name: 'eraser',
    text: 'Eraser tool',
    shift: '',
    ctrl: '',
    key: 'E',
  },
  {
    name: 'bucket',
    text: 'Paint bucket tool',
    shift: '',
    ctrl: '',
    key: 'B',
  },
  {
    name: 'line',
    text: 'Stroke tool',
    shift: '',
    ctrl: '',
    key: 'L',
  },
  {
    name: 'rectangle',
    text: 'Rectangle tool',
    shift: '',
    ctrl: 'Keep 1 to 1 ratio',
    key: 'R',
  },
  {
    name: 'drawEllipsis',
    text: 'Circle tool',
    shift: '',
    ctrl: 'Keep 1 to 1 ratio',
    key: 'C',
  },
  {
    name: 'dithering',
    text: 'Dithering',
    shift: '',
    ctrl: '',
    key: 'T',
  },
  {
    name: 'lighten',
    text: 'Lighten',
    shift: '',
    ctrl: 'Darken',
    key: 'U',
  },
  {
    name: 'fillRectangle',
    text: 'Rectangle selection',
    shift: '',
    ctrl: '+ C. Copy the selected aria. CTRL: + V paste the copied aria ',
    key: 'S',
  },
  {
    name: 'paintAll',
    text: 'Point all pixels of the same color',
    shift: '',
    ctrl: '',
    key: 'A',
  },
  {
    name: 'move',
    text: 'Move tool',
    shift: '',
    ctrl: '',
    key: 'M',
  },
  {
    name: 'shape',
    text: 'Shape selection',
    shift: '',
    ctrl: '',
    key: 'Z',
  },
  {
    name: 'picker',
    text: 'Color picker',
    shift: '',
    ctrl: '',
    key: 'O',
  },
];

export default toolInfo;
